### PR TITLE
Fix #11: Update Spring Boot version to the latest

### LINKED ISSUE #11: Update Spring Boot version to the latest
As a **user**, I want to update the Spring Boot version to the latest **so that** I can have this project up to date.

**Acceptance Criteria**
- I am able to see Spring Boot version: `3.1.2` in the `build.gradle` file
- Project tests are passing

### PR DESCRIPTION
**Pull request by ducksblock**
#### This fixes #11

Updated the gradle version to 3.1.2

### CODE REVIEW

**Comment by josdem** [comment]
Hi @ducksblock, thanks for your PR. Is `dependency-management` the correct version?

**Comment by ducksblock** [comment]
I am not sure about that. If you can provide me some info on how I can check that then it'd be great.

**Comment by josdem** [comment]
> I am not sure about that. If you can provide me some info on how I can check that then it'd be great.

Hi @ducksblock I know a couple of options:
- You can run `spring init` command to create a project with recent Spring boot dependencies and versions; for more information, please go [here](https://josdem.io/techtalk/spring/spring_webflux_basics/)
- You can create a new zip file with a new project structure using [https://start.spring.io/](https://start.spring.io/). I am adding an image as a reference.
springInitializr

I hope this helps.

**Comment by ducksblock** [comment]
Hi @josdem ! 

I have updated the spring `dependency-management` version. Thanks for the help :)

**Review by josdem — APPROVED** [review]
Looks good, thanks @ducksblock I appreciate your collaboration!

**Pull request merged**
